# Generated by Django 5.2.6 on 2025-10-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='created_at',
            new_name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='published_time',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.TextField(),
        ),
    ]
