# Generated by Django 5.2.6 on 2025-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_rename_url_newsarticle_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date', '-scraped_at']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
