# Generated by Django 5.2.6 on 2025-10-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_newsarticle_options_newsarticle_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-scraped_at']},
        ),
    ]
