# Generated by Django 5.2.6 on 2025-10-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={},
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
